<?php

namespace Mallto\Tool\Domain\NewConfig;

use RuntimeException;

class NewConfigEnvFile
{
    public function write(array $values, ?string $filepath = null): array
    {
        $filepath = $filepath ?: storage_path('framework/new_configs.env');
        $values = $this->normalizeValues($values);
        $content = $this->renderContent($values);

        if (is_file($filepath) && is_readable($filepath) && $content === (string)file_get_contents($filepath)) {
            return [
                'changed' => false,
                'backup_path' => null,
                'env_path' => $filepath,
            ];
        }

        $this->atomicWrite($filepath, $content);

        return [
            'changed' => true,
            'backup_path' => null,
            'env_path' => $filepath,
        ];
    }

    public function renderContent(array $values): string
    {
        $values = $this->normalizeValues($values);
        $lines = [
            '# Generated by easy-tool new_configs.',
            '# Source this file before starting LaravelS or Horizon.',
        ];

        foreach ($values as $key => $value) {
            $lines[] = 'export ' . $key . '=' . $this->shellQuote($value);
        }

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    private function normalizeValues(array $values): array
    {
        $normalized = [];
        foreach ($values as $key => $value) {
            $key = strtoupper(trim((string)$key));
            if ($key === '') {
                continue;
            }

            if (preg_match('/^[A-Z_][A-Z0-9_]*$/', $key) !== 1) {
                throw new RuntimeException("Invalid env key [{$key}]");
            }

            $normalized[$key] = (string)$value;
        }

        ksort($normalized);

        return $normalized;
    }

    private function shellQuote(string $value): string
    {
        return "'" . str_replace("'", "'\"'\"'", $value) . "'";
    }

    private function atomicWrite(string $filepath, string $content): void
    {
        $directory = dirname($filepath);
        if (!is_dir($directory)) {
            throw new RuntimeException("Runtime env directory does not exist: {$directory}");
        }

        $tmpPath = $directory . '/.' . basename($filepath) . '.' . getmypid() . '.tmp';
        if (file_put_contents($tmpPath, $content, LOCK_EX) === false) {
            throw new RuntimeException("Failed to write temporary runtime env file: {$tmpPath}");
        }

        $directoryGroup = @filegroup($directory);
        if ($directoryGroup !== false) {
            @chgrp($tmpPath, $directoryGroup);
        }
        @chmod($tmpPath, 0660);

        if (!rename($tmpPath, $filepath)) {
            @unlink($tmpPath);
            throw new RuntimeException("Failed to replace runtime env file: {$filepath}");
        }

        @chmod($filepath, 0660);
    }
}
